version: "3.8"

services:
  web-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - ./env/.env
    volumes:
      - type: bind
        source: ./logs/api.log
        target: /app/logs/api.log
      - type: bind
        source: ./logs/api.err.log
        target: /app/logs/api.err.log
    networks:
      - backend
#    depends_on:
#      - "db"
#      - "redis"
#  db:
#    image: mysql:latest
#    expose:
#      - 3306
#    volumes:
#      - type: volume
#        source: db_data
#        target: /var/lib/mysql
#        volume:
#          nocopy: true
#    networks:
#      - backend
#    env_file:
#      - ./env/.env
#    environment:
#      MYSQL_DATABASE: ${DB_NAME}
#      MYSQL_ROOT_PASSWORD: ${DB_PASS}
#  redis:
#    image: redis:latest
#    expose:
#      - 6379
#    networks:
#      - backend
#    env_file:
#      - ./env/.env
#
#volumes:
#  db_data:

networks:
  backend: